default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: <%= Rails.application.credentials.dig(:database_password) %>
  database: koombea_contact

test:
  <<: *default

development:
  <<: *default

production:
  adapter: postgresql
  host: <%= Rails.application.credentials.dig(:production_database_host) %>
  port: 5432
  username: <%= Rails.application.credentials.dig(:production_database_user) %>
  password: <%= Rails.application.credentials.dig(:production_database_pass) %>
  database: <%= Rails.application.credentials.dig(:production_database_name) %>
