default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: <%= Rails.application.credentials.dig(:database_password) %>
  database: koombea_contact

development:
  <<: *default

production:
  <<: *default
